### PR TITLE
Add Fedora linux dependencies

### PR DESCRIPTION
**Pull request by bkmgit**
Should be similar for RHEL, Rocky Linux, Alma Linux, Oracle Linux, Vine Linux, Red Flag Linux

### CODE REVIEW

**Review by VincentWei — COMMENTED** [review]
I checked on Ubuntu 22.04, the package name for FreeType 2 development is called `libfreetype-devel`.

**Review by VincentWei — APPROVED** [review]

**Comment by bkmgit** [comment]
In Fedora it is freetype-devel https://packages.fedoraproject.org/pkgs/freetype/freetype/

Do you wish to change
```
$ sudo apt install git g++ binutils autoconf automake libtool make cmake pkg-config
$ sudo apt install libgtk2.0-dev
$ sudo apt install libjpeg-dev libpng-dev libfreetype6-dev libharfbuzz-dev
$ sudo apt install libinput-dev libdrm-dev libsqlite3-dev libxml2-dev libssl1.0-dev
```
to
```
$ sudo apt install git g++ binutils autoconf automake libtool make cmake pkg-config
$ sudo apt install libgtk2.0-dev
$ sudo apt install libjpeg-dev libpng-dev libfreetype-dev libharfbuzz-dev
$ sudo apt install libinput-dev libdrm-dev libsqlite3-dev libxml2-dev libssl1.0-dev
```
For Ubuntu 22.04?

Should OpenSSL be updated to 3?
Can libwebp be added?

**Comment by VincentWei** [comment]
On Ubuntu 22.04, `libfreetype6-dev` is marked as a `transitional package`. Does this mean that we should no longer use `libfreetype6-dev`?

And I also noticed that `libssl-dev` package is also available on Ubuntu 22.04; The version is 3.0.2. Therefore, should we use `libssl-dev` instead?

> Can libwebp be added?

Yes, it should be.

Thanks a lot!

**Comment by bkmgit** [comment]
Updated. Openssl 3 and libfreetype work on Fedora.

**Pull request merged**
